import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { Inter } from 'next/font/google'
import { SettingsProvider } from './context/SettingsContext'
import { isDevMode } from './lib/dev'
import appInfo from './lib/app'
import { DEFAULT_THEME } from './app_settings'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: appInfo.appName,
  applicationName: appInfo.appName,
  description: `Generated by ${appInfo.appName}`,
  other: {
    version: appInfo.appVersion,
  },
}

const defaultAppSettings = {
  dev: isDevMode(),
  theme: DEFAULT_THEME,
}

const DynamicLayout = dynamic(() => import('./ui/Layout'), { ssr: false })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SettingsProvider value={{ defaultValues: defaultAppSettings }}>
          <DynamicLayout title={<>{metadata.title}</>} drawer={{}}>
            {children}
          </DynamicLayout>
        </SettingsProvider>
      </body>
    </html>
  )
}
